# ══ Names ═══════════════════════════════════════════════════════════════════ #
#    -----                                                                     #

NAME 				= libasm.out

# ══ Colors ══════════════════════════════════════════════════════════════════ #
#    ------                                                                    #

DEL_LINE 			= \033[2K
ITALIC 				= \033[3m
BOLD 				= \033[1m
DEF_COLOR 			= \033[0;39m
GRAY 				= \033[0;90m
RED 				= \033[0;91m
GREEN 				= \033[0;92m
YELLOW 				= \033[0;93m
BLUE 				= \033[0;94m
MAGENTA 			= \033[0;95m
CYAN 				= \033[0;96m
WHITE 				= \033[0;97m
BLACK 				= \033[0;99m
ORANGE 				= \033[38;5;209m
BROWN 				= \033[38;2;184;143;29m
DARK_GRAY 			= \033[38;5;234m
MID_GRAY 			= \033[38;5;245m
DARK_GREEN 			= \033[38;2;75;179;82m
DARK_YELLOW 		= \033[38;5;143m

# ══ Compilation══════════════════════════════════════════════════════════════ #
#    -----------                                                               #

CC 					= clang
AR 					= ar rcs
RM 					= rm -f
MK 					= make -C
MKD					= mkdir -p
MCL 				= make clean -C
MFCL 				= make fclean -C
MK_					= && make

# ══ Directories ═════════════════════════════════════════════════════════════ #
#    -----------                                                               #

LIBASM_DIR			= ./libasm
OBJ_DIR				= ./obj 
SRC_DIR				= ./src
INC_DIR				= ./includes
UTILS_DIR			= ./utils

# ══ Bonus Directories ═══════════════════════════════════════════════════════ #
#    -----------------                                                         #

SRC_BONUS_DIR		= ./src_bonus
INCLUDES_BONUS_DIR	= ./includes_bonus

# ══ Flags ═══════════════════════════════════════════════════════════════════ #
#    -----                                                                     #

CFLAGS 				= -Wall -Werror -Wextra
IFLAGS				= -I${INC_DIR}

# ══ Flags Bonus══════════════════════════════════════════════════════════════ #
#    -----------                                                               #

IFLAGS_BONUS		= -I${INCLUDES_BONUS_DIR}


# ══ Sources ═════════════════════════════════════════════════════════════════ #
#    -------                                                                   #

SRC 				= ${SRC_DIR}/main.c

LBA 				= ${LIBASM_DIR}/ft_strlen.s \
					  ${LIBASM_DIR}/ft_strcpy.s \
					  ${LIBASM_DIR}/ft_strcmp.s \
					  ${LIBASM_DIR}/ft_write.s \
					  ${LIBASM_DIR}/ft_read.s \
					  ${LIBASM_DIR}/ft_strdup.s




OBJ_SRC				= $(patsubst ${SRC_DIR}/%.c, ${OBJ_DIR}/%.o, ${SRC})
OBJ_LBA				= $(patsubst ${LIBASM_DIR}/%.s, ${OBJ_DIR}/%.o, ${LBA})

# ══ Sources Bonus ═══════════════════════════════════════════════════════════ #
#    -------------                                                             #

SRC_BONUS			= ${SRC_BONUS_DIR}/checker_bonus.c

OBJ_SRC_BONUS		= $(patsubst ${SRC_BONUS_DIR}/%.c, ${OBJ_DIR}/%.o, \
						${SRC_BONUS})

# ═══ Rules ══════════════════════════════════════════════════════════════════ #
#     -----                                                                    #

all: ${NAME}

${NAME}: ${OBJ_SRC} ${OBJ_LBA}
	@echo "$(YELLOW)Compiling root ...$(DEF_COLOR)"
	@${CC} ${CFLAGS} ${IFLAGS} -o ${NAME} ${OBJ_SRC} ${OBJ_LBA}
	@echo "$(GREEN) $(NAME) all created ✓$(DEF_COLOR)"

${OBJ_DIR}/%.o: ${SRC_DIR}/%.c
	@${MKD} $(dir $@)
	@echo "$(CYAN)Compiling $<...$(DEF_COLOR)"
	@$(CC) ${CFLAGS} ${IFLAGS} -c $< -o $@

${OBJ_DIR}/%.o: ${LIBASM_DIR}/%.s
	@${MKD} $(dir $@)
	@echo "$(CYAN)Assembling $<...$(DEF_COLOR)"
	@nasm -f elf64 $< -o $@

# ══ Rules Bonus══════════════════════════════════════════════════════════════ #
#    -----------                                                               #

bonus:
	@echo "$(YELLOW)Bonus not implemented yet$(DEF_COLOR)"


clean:
	@echo "$(YELLOW)Removing object files ...$(DEF_COLOR)"
	@${RM} -r ${OBJ_DIR}
	@echo "$(RED)Object files removed $(DEF_COLOR)"

fclean:	clean
	@echo "$(YELLOW)Removing binaries ...$(DEF_COLOR)"
	@${RM} ${NAME}
	@echo "$(RED)Binaries removed $(DEF_COLOR)"

re:	fclean all

.PHONY : all clean fclean bonus re